### PR TITLE
Tests for zephir parser

### PR DESCRIPTION
**Pull request by davidofferman**
Hello!
Here are a few new tests so far for the parser. I'm going to continue pushing more tests to this branch, so if you want to hold off on merging, that will be fine.

Hopefully this will greatly improve code coverage so I can start working on getting the language to support uppercase classes, methods, and possibly variables.

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/php-zephir-parser/blob/master/CONTRIBUTING.md)
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I wrote some tests for this PR.

Thanks

### CODE REVIEW

**Comment by davidofferman** [comment]
While looking at the build script, I think there is a problem with code coverage generation. The codecov bash script uses `find -execdir` to run gcov, which changes the directory. The `package.mk` file strips the absolute path from the `#line` directives.

```
File 'parser/zephir.lemon'
Lines executed:34.80% of 1138
Branches executed:80.00% of 10
Taken at least once:50.00% of 10
Calls executed:30.70% of 1267
Creating 'parser#zephir.lemon.gcov'
Cannot open source file parser/zephir.lemon
```
https://travis-ci.org/phalcon/php-zephir-parser/jobs/561353443#L798

**Is there a reason why we strip the absolute path from `scanner.c` and `parser.c`?** Also I will need to change the hack-ish `base.c` line directive when generating `parser.c` to use `$(top_srcdir)`.

https://github.com/phalcon/php-zephir-parser/blob/ca800dcd20b9af3c55a69a8b2799e5e1ca9dd05c/parser.mk#L41

**Comment by sergeyklay** [comment]
Feel free to remove this logic from parser.mk as a far we no longer store parser.c and acenner.c under the version control.

**Comment by davidofferman** [comment]
Hello,
For now I'm done with writing test code. You can look over the code and merge if you approve it.

In `zephir.lemon` when we set the nonterminal of `xx_declare_statement`, we leave out the types of `TYPE_RESOURCE`, `TYPE_CALLABLE` and `TYPE_OBJECT`. I couldn't find enough documentation to determine if those should be added to the allowed types for declare statements or if I should remove them from `parser.h` in the function `xx_ret_declare_statement()`.

Thank you.

**Comment by sergeyklay** [comment]
As a far as I remember it was not finished. Do you have a reasonable proposition to work with those types? But at the moment it seems good to me. Thank you!

**Comment by davidofferman** [comment]
I'm not sure if those types have any real purpose. In the zephir project, variables defined with those types are just set to the type `variable`. For now I'm going to leave it alone.

https://github.com/phalcon/zephir/blob/1b56924c834707de43db1a2002d1f16b64238b11/Library/Variable.php#L177

```
class Variable implements TypeAwareInterface
{
    public function __construct($type, $name, Branch $branch = null)
    {
        $this->globalsManager = new Globals();

        if (\in_array($type, ['callable', 'object', 'resource'], true)) {
            $type = 'variable';
        }

        $this->type = $type;
        $this->name = $name;
        $this->branch = $branch;
    }
}
```

Thanks you for your time and for reviewing all that code.

**Pull request merged**
